### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by infotechnohelp** [infotechnohelp/genolines#1]
- [ ] Variable types → string, integer, boolean, array
- [ ] Map of types and allowed modifiers
- [ ] Genolines method 
- [ ] Own line query: after({ ' ': ''}), before, exactly, between
- [ ] line identifier by regex + options ( all, exactly (index),  after(index), before (index) )
- [ ]
